---
  - name: Get disk facts
    win_disk_facts:

  - name: Initialize Disk
    win_shell: "Initialize-Disk -Number {{ disk_number }}"
    when: ansible_disks[disk_number].guid is none

  - name: Create Partition using all available space
    win_partition:
      drive_letter: "{{ disk_drive_letter }}"
      partition_size: -1
      disk_number: "{{ disk_number }}"
    when: ansible_disks[disk_number].partitions[1] is undefined

  - name: Format the partition as NTFS and label it
    win_format:
      drive_letter: "{{ disk_drive_letter }}"
      file_system: NTFS
      new_label: "{{ disk_drive_label }}"
    when: ansible_disks[disk_number].partitions[1].volumes is undefined
