galaxy_info:
  role_name: importpfx
  author: Joe Shonk
  description: Import PFX from an SMB Share Location
  company: The Shonk Project

  license: GPL-3.0-only

  min_ansible_version: 2.9

  platforms:
   - name: Windows
     versions:
     - 2016
     - 2019

  galaxy_tags:
    - certificate
    - pfx

dependencies: []
