galaxy_info:
  role_name: configure_addition_disk
  author: Joe Shonk
  description: Configure Second Disk - Initialize, Format, and Assign Drive Letter
  company: The Shonk Project

  license: GPL-3.0-only

  min_ansible_version: 2.9

  platforms:
   - name: Windows
     versions:
     - 2016
     - 2019

  galaxy_tags:
    - disk

dependencies: []
