galaxy_info:
  role_name: secure_winrm
  author: Joe Shonk
  description: Disallows Unencypted Traffic, Removes Port 80, and Removes Basic Authentication
  company: The Shonk Project

  license: GPL-3.0-only

  min_ansible_version: 2.9

  platforms:
   - name: Windows
     versions:
     - All

  galaxy_tags:
    - winrm

dependencies: []
